### ISSUE TITLE
Final Submission Document

### ISSUE THREAD

**Issue by mspagon** [ericaddison/APT_miniProject_Android#20]
We can start thinking about what to write - I created a skeleton here.

Same steps as before...

https://docs.google.com/document/d/1wPq_o3Hz917KLUXINdw14fpZtPZTuYW7vdzrXiXGeO0/edit

**Comment by ericaddison** [comment]
Thanks. I'll poke at this today.

**Comment by mspagon** [comment]
Looks like we have to create a video capture of us navigating the app.

**Comment by ericaddison** [comment]
Gd! And it explicitly wants to see the pagination for more than 16 images on a stream...

**Comment by ericaddison** [comment]
@mspagon 
Hey Mike, I don't know if you saw, but I can't access the report. Is it shared?

**Comment by mspagon** [comment]
Yea. I did file new inside a new document thinking it would be in the same directory.  It wasn't.

It is now there. 

Sorry

**Comment by mspagon** [comment]
You will have until **11/04/2017 at 11:59 pm** to either add the video link to your report or perform the live demo.

Below are the instructions for your demo. The setup portion should be completed prior to the live demo (or prior to starting the video recording).

 

Setup (i.e., make sure the following has occurred prior to the demo):

1. Make sure that at least 5 streams exist.

2. Make sure that each stream contains at least 1 image.

3. Make sure that one of the streams contains more than 16 images.

4. Make sure that the user is subscribed to at least 1 stream.

 

Demo:

1. Log in

2. View all streams (Main activity)

3. Enter a stream that has more than 16 images and demo the pagination.

4. Go back to Main activity.

5. Select my subscribed streams.

6. Navigate to the first subscribed stream.

7. Upload an image from your library

8. Upload another image by taking a picture. Tag the image as “pumpkin”

9. Go back to the main activity

10. View nearby pictures and find the ones that just got uploaded.

11. Go back to the main activity

12. Select my subscribed streams (The most recently uploaded image should appear as the cover for the corresponding stream).

13. Search for the stream with the text “pumpkin”

14. Navigate to the resulting stream.

**Comment by ericaddison** [comment]
Ok let's see... we need to get in search and stream pagination still. Both should be very easy. 

For pagination, we should just limit the number of images that are displayed in the gridview at a time to 16, and track the starting index, incrementing it by 16 when user presses more.

For search, that should happen on the same activity as view all streams, but make an api call to the search service (might need to make another search service that returns info instead of just stream ids), and then update grid view contents like how the subscribed stream button works.

For you uplpad, @mspagon, keep pushing if you can. We can talk on the phone today to try and get it ironed out.

**Comment by mspagon** [comment]
Sweet sounds good, just going to sleep now and working from home.  I'll be up and free to talk sometime around 2-9. just ping me on google chat or something and we can chat!

**Comment by mspagon** [comment]
Oh and just in case you didn't see:
Even though the github code and submission document is due tonight,
we don't have to demonstrate the app until 11/04/2017 at 11:59 pm.

**Comment by psigourney** [comment]
>>Even though the github code and submission document is due tonight,
we don't have to demonstrate the app until 11/04/2017 at 11:59 pm.

awesome possum!

**Comment by mspagon** [comment]
Submitted:

https://docs.google.com/document/d/1wPq_o3Hz917KLUXINdw14fpZtPZTuYW7vdzrXiXGeO0/

Changes are still good until midnight.

![image](https://user-images.githubusercontent.com/5027451/32130489-ff13ded8-bb5e-11e7-935f-38de85f9e5a5.png)


Thanks.

**Comment by ericaddison** [comment]
Thanks man! I added the last "Mistakes" bullet and added a few more screen shots.

GOOD DAMN WORK everyone!

**Comment by mspagon** [comment]
adding the youtube video link to google drive submission document.

https://www.youtube.com/watch?v=yQw4ljAlyjs&feature=youtu.be

**Comment by ericaddison** [comment]
@mspagon 
Wow! Nice work! Even with the tags!

You've got a great naration voice :)
