### ISSUE TITLE
How to use ServerCommunicator.java

### ISSUE THREAD

**Issue by mspagon** [ericaddison/APT_miniProject_Android#9]
I see that you are using Volley to perform HTTP requests?  I also see that you created a ServerCommunicator class.  Can you please explain how I can use this class to query our NDB by calling GET requests to /services/?

What confuses me is the callback action in the method arguments:

public void requestAllStreamInfoData(ServerResponseAction callbackAction){

What is callbackAction doing?

Thanks for the help.

**Comment by mspagon** [comment]
Oh I see usages in your TestActivity.java.

This might help me.

**Comment by mspagon** [comment]
Hmm just found out I had build error all this time that made it so the APK wasn't uploaded to virtual device, no wonder nothing was working.  Need to resolve this.

**Comment by mspagon** [comment]
Got what I need working for now.

Thanks.

**Comment by ericaddison** [comment]
Cool! Let me know if more comes up :)
